### PR TITLE
Add native origins for reference spaces

### PR DESCRIPTION
**Pull request by Manishearth**
I just noticed we're not clear about this.

I'd also like @cabanier to double check my axes.

***
<a href="https://pr-preview.s3.amazonaws.com/Manishearth/webxr/pull/1350.html" title="Last updated on Oct 2, 2023, 11:35 PM UTC (b5f3142)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1350/9a0cb83...Manishearth:b5f3142.html" title="Last updated on Oct 2, 2023, 11:35 PM UTC (b5f3142)">Diff</a>

### CODE REVIEW

**Comment by cabanier** [comment]
Are we not clear about this? I thought there was a general description of how spaces are oriented in the spec.

**Comment by Manishearth** [comment]
We say above 

> The native origin for every XRReferenceSpace describes a coordinate system where +X is considered "Right", +Y is considered "Up", and -Z is considered "Forward"

I think it's useful to have this inline. I'm not 100% sure.

**Comment by cabanier** [comment]
Do we call this out in all the other spec? for instance, do we do it for anchors?

**Comment by Manishearth** [comment]
We do this in this spec for target ray / grip spaces. We _should_ do this everywhere; we need to be precise.

**Comment by cabanier** [comment]
I'm not sure. I think defining the default in WebXR is enough. If a spec wants to digress, it can call it out.

**Comment by Manishearth** [comment]
I think the problem is that "forward" and "up" are extremely relative terms. Which I still use here but in some contexts more precisely.

**Comment by Manishearth** [comment]
In general I think part of the problem is that the definitions of these native origins is not fully discoverable since the spot that defines the native origins doesn't reference the X/Y/Z stuff. We could tighten it up with a "standard XR orientation" definition that we reference.

**Comment by cabanier** [comment]
> In general I think part of the problem is that the definitions of these native origins is not fully discoverable since the spot that defines the native origins doesn't reference the X/Y/Z stuff. We could tighten it up with a "standard XR orientation" definition that we reference.

That sounds like the correct way to solve this.

**Comment by Manishearth** [comment]
Thinking about this more I think the status quo is fine.

**Pull request closed without merging**
