### PR TITLE
Fix typo https://github.com/immersive-web/webxr/commit/4ab6792378859c…

### PR DESCRIPTION
**Pull request by jungkees**
…4e38120ff7ad352da893d3c99e introduced

### CODE REVIEW

**Comment by jungkees** [comment]
s/a/an/ that I missed in the previous commit.

**Comment by ddorwin** [comment]
Please clean up the commit message when merging. For example, `Fix typo in 4ab6792`.

Note: You can change it here, but GitHub might revert to the original one in the commit message, at least when choosing to squash.

**Comment by jungkees** [comment]
I just cleaned up the commit message as suggested.

**Comment by toji** [comment]
Thanks for the fix! Made sure the cleaner commit message was the one that stuck.

**Pull request merged**
