### PR TITLE
[WIP] material used for 2022/03/29 CR publication

### PR DESCRIPTION
**Pull request by himorin**
lines added for upcoming 2022/03/29 CR publication

***
<a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/pull/1261.html" title="Last updated on Apr 1, 2022, 6:22 AM UTC (fa48ada)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/webxr/1261/66f8949...fa48ada.html" title="Last updated on Apr 1, 2022, 6:22 AM UTC (fa48ada)">Diff</a>

### CODE REVIEW

**Review by toji — APPROVED** [review]
Changes look good at this point, approving preemptively. Let us know if any changes/additions need a re-review before it's time to land.

**Comment by himorin** [comment]
CR material out with this PR applied.
how do you want to archive (or tagging in github?) for this release? I think we've tagged for FPWD

note, for streamlined publication as CRD, none of lines with this PR are used (or just ignored for status, date and deadline).

**Review by Manishearth — APPROVED** [review]

**Comment by Manishearth** [comment]
> how do you want to archive (or tagging in github?) for this release? I think we've tagged for FPWD

We can probably tag it as `cr`? I'm not sure what we need here.

Also, @himorin, is there a reason this is just this spec and not the AR/Gamepads modules as well? Or are those going to happen after this one hits CR?

**Comment by himorin** [comment]
> Also, @himorin, is there a reason this is just this spec and not the AR/Gamepads modules as well? Or are those going to happen after this one hits CR?

As in the last IWWG call, we first need to prepare HR self review check lists, and pass HRs with completed lists.

**Comment by himorin** [comment]
merging this, and will tag as CRS-20220331 asap.

**Pull request merged**
