### PR TITLE
summarized #718, #719, and #875 about immersive UIs

### PR DESCRIPTION
**Pull request by avadacatavra**

### CODE REVIEW

**Comment by Manishearth** [comment]
You'll need to check off IPR by linking GitHub to w3c: https://labs.w3.org/repo-manager/pr/id/immersive-web/webxr/916

**Comment by avadacatavra** [comment]
@Manishearth just did that--is there a try/retry?

**Comment by Manishearth** [comment]
"turn it off and on again"

**Comment by toji** [comment]
LGTM!

**Pull request merged**
