### PR TITLE
Update Oculus to Meta Quest

### PR DESCRIPTION
**Pull request by cabanier**
Rename oculus, rift to meta, quest

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]
rip

**Review by toji — COMMENTED** [review]
🫡

**Comment by himorin** [comment]
wait, why it's merged against master but not main?

**Comment by cabanier** [comment]
> wait, why it's merged against master but not main?

I didn't know there was a `main` and a `master`. Which one should be updated?

**Comment by alcooper91** [comment]
Coming at this late, I was under the impression that `main` is what needs to be updated as the "Code" page shows my merge as the latest by default.

**Comment by cabanier** [comment]
@himorin can we delete the branches that are obsolete?
I'll resubmit my PR afterwards.

**Pull request merged**
