### PR TITLE
Add text explaining the depth range values.

### PR DESCRIPTION
**Pull request by toji**
Not much to say about this one. Resolves longstanding issue #120. Inclined to push this soon if there's no comments about it. The only possible concern I could see others having is the specification that changes to the depth values take effect on the next frame.

### CODE REVIEW

**Comment by toji** [comment]
@leweaver and the rest of the Microsoft crew asked for some time on the previous Immersive Web call to evaluate this change and ensure it works with their platform. If the answer is yes then I'll merge it because otherwise it seemed to be non-controversial.

**Comment by leweaver** [comment]
Sorry for the delayed response @toji - we've been talking about this in depth (puns aside!) over the past few days. 

We are happy that this change will work on our platform and for it to be merged - but would also like to mention that in-frame changes to the near/far values are no longer restricted to taking effect on the next frame on our platform. This could possibly remove the need for text to that effect in this change?

**Comment by toji** [comment]
For me the mid-frame restriction is actually more about predictability of content than a platform restriction. If you change the depth range mid-frame then anything you've rendered to that point will no longer depth-test properly, and it's possible that some reprojection techniques would begin to fail.

**Comment by blairmacintyre** [comment]
Regarding @kearwood's comment:  what is the relationship to logarithmic depth?  In many of our AR demos with Argon, that used geospatial content, we used logarithmic depth so we could use "very large values" (e.g., put things on the other side of the planet).  If this isn't possible, it can be worked around, but it can be a pain.

**Pull request merged**
