### PR TITLE
added index.html to .gitignore

### PR DESCRIPTION
**Pull request by himorin**
to prevent events similar to https://github.com/immersive-web/webxr/pull/1184#pullrequestreview-616972241

(do we need to keep node/npm related lines used(??) for TravisCI?)

### CODE REVIEW

**Comment by toji** [comment]
We may need to revert this. The reason why this wasn't part of the ignored files previously is because our hook to publish the rendered spec to the gh_pages branch was failing to commit the index.html if that was there. We should verify whether or not that's still happening, and if so either revert this change or update our Travis scripts to remove it prior to pushing the published changes.

**Comment by Manishearth** [comment]
ah oops

The publish step should perhaps force add it

**Comment by himorin** [comment]
We might need smarter one, but current deploy script explicitly excludes gitignore, so I believe we will not have that again.

https://github.com/immersive-web/webxr/blob/main/.github/workflows/deploy.yml#L18
>        run: mkdir deploy && rsync -av --exclude=.git --exclude=.gitignore --exclude=deploy . deploy/

**Comment by toji** [comment]
Ah, good to know! Thank you!

**Pull request merged**
